import { Poppins } from 'next/font/google'
import Sidebar from '../components/Sidebar'

const poppins = Poppins({
  weight: ['400', '600', '700'],
  subsets: ['latin']
})
export const metadata = {
  title: 'Stacher',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div>
          <div>
            <Sidebar />
          </div>
          <div className='ml-80'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
